### ISSUE TITLE
Issue when running on Linux Mint

### ISSUE THREAD

**Issue by wlgrd** [gregkh/lsusb#1]
$ python lsusb.py 
```
Traceback (most recent call last):
  File "lsusb.py", line 499, in <module>
    main(sys.argv)
  File "lsusb.py", line 491, in main
    parse_usb_ids()
  File "lsusb.py", line 102, in parse_usb_ids
    for ln in file(usbids, "r").readlines():
IOError: [Errno 2] No such file or directory: '/usr/share/usb.ids'
```
Python 2.7.15+ (default, Jul  9 2019, 16:51:35) 
[GCC 7.4.0] on linux2

**Comment by yyihuan** [comment]
the same problem is in ubuntu22.04
